apiVersion: v1
kind: Service
metadata:
  name: voltha
  namespace: voltha
  labels:
    name: voltha
spec:
  type: NodePort
  ports:
    - name: rest
      port: 8882
      nodePort: 32082
    - name: mystery
      port: 8001
      nodePort: 32001
    - name: mystery2
      port: 8443
      nodePort: 32443
    - name: grpc
      port: 50555
      nodePort: 30555
  selector:
    app: voltha
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: voltha
  namespace: voltha
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: voltha
    spec:
      containers:
        - name: voltha
          image: docker-repo.dev.atl.foundry.att.com:5000/voltha-envoy:1.1
          env:
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          args:
            - "/usr/local/bin/envoyd"
            - "-envoy-cfg-template=/envoy/voltha-grpc-proxy.template.json"
            - "-envoy-config=/envoy/voltha-grpc-proxy.json"
            - "-kv=etcd"
            - "-kv-svc-name=etcd.$(NAMESPACE).svc.cluster.local"
            - "-kv-port=2379"
       #      - "/bin/sh"
       #      - "-ecx"
       #      - |
       #       sleep 1000

          ports:
            - containerPort: 8882
              name: rest-port
            - containerPort: 8001
              name: mystery-port
            - containerPort: 8443
              name: mystery2-port
            - containerPort: 50555
              name: grpc-port
          imagePullPolicy: IfNotPresent


