apiVersion: v1
kind: Service
metadata:
  name: kafka
  namespace: voltha
spec:
  clusterIP: None
  selector:
    app: kafka
  ports:
  - protocol: TCP
    port: 9092
    targetPort: 9092
---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: kafka
  namespace: voltha
spec:
  serviceName: kafka
  replicas: 1
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
      annotations:
        cni: "calico"
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: kafka
        image: wurstmeister/kafka:1.0.0
        volumeMounts:
        - name: kafka-data
          mountPath: /kafka
        ports:
        - containerPort: 9092
        env:
        - name: KAFKA_ADVERTISED_PORT
          value: "9092"
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: zoo:2181
        - name: KAFKA_HEAP_OPTS
          value: "-Xmx256M -Xms128M"
      volumes:
      - name: kafka-data
        hostPath:
          path: /var/lib/voltha-runtime/kafka
          type: Directory
