apiVersion: v1
kind: Service
metadata:
  name: kibana
  namespace: voltha
  labels:
    name: kibana
spec:
  type: NodePort
  ports:
    - name: rest
      port: 8080
      nodePort: 31079
  selector:
    app: kibana

---

apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: kibana
  namespace: voltha
  labels:
    k8s-app: kibana
    kubernetes.io/cluster-service: "true"
    addonmanager.kubernetes.io/mode: Reconcile
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: kibana
  template:
    metadata:
      labels:
        k8s-app: kibana
      annotations:
        seccomp.security.alpha.kubernetes.io/pod: 'docker/default'
    spec:
      containers:
      - name: kibana
        image: docker.elastic.co/kibana/kibana-oss:6.3.2
        resources:
          # need more cpu upon initialization, therefore burstable class
          limits:
            cpu: 1000m
          requests:
            cpu: 100m
        env:
          - name: ELASTICSEARCH_URL
            value: http://elasticsearch-logging:9200
          - name: SERVER_BASEPATH
            value: /api/v1/namespaces/kube-system/services/kibana/proxy
        ports:
        - containerPort: 5601
          name: ui
          protocol: TCP



