# ATT SEBA Voltha Helm Values

kafkaReleaseName: cord-kafka

#application_logs: |
#  log4j.logger.org.opencord.olt = DEBUG
#  log4j.logger.org.opencord.kafka = DEBUG
#  log4j.logger.org.opencord.sadis = DEBUG
#  log4j.logger.org.opencord.aaa = DEBUG
