onosImage: "docker-repo.dev.atl.foundry.att.com:5000/onosproject/onos:jono"

services:
  openflowServiceType: NodePort
  ovsdbServiceType: NodePort
  sshServiceType: NodePort
  uiServiceType: NodePort
  ovsdb:
    nodePort: 31640
  openflow:
    nodePort: 31653
  ssh:
    nodePort: 31101
  ui:
    nodePort: 31181

onos_env:
  - name: ONOS_APPS
    value: "openflow"

xos_service_label: ONOS_Fabric
