version: 1

formatters:
  default:
    format: '%(asctime)s.%(msecs)03d %(levelname)-8s %(threadName)s %(module)s.%(funcName)s %(message)s'
    datefmt: '%Y%m%dT%H%M%S'

handlers:
  console:
    class : logging.StreamHandler
    formatter: default
    stream: ext://sys.stdout

loggers:
  '':
    handlers: [console]
    level: DEBUG
    propagate: False
